package com.tencent.qqnt.kernel.nativeinterface;

public class GroupAllInfo {
    public int appealDeadline;
    public int certType;
    public int classExt;
    public int cmdUinFlagEx2;
    public int cmdUinJoinTime;
    //public GroupMsgMask cmdUinMsgMask;
    public int cmdUinMsgSeq;
    //public MemberRole cmdUinPrivilege;
    public int cmdUinUinFlag;
    public String fingerMemo;
    public String groupAnswer;
    public long groupCode;
    public int groupFlag;
    public int groupFlagExt;
    public int groupFlagExt3;
    public int groupFlagExt4;
    public String groupMemo;
    public String groupName;
    public int groupOption;
    public String groupQuestion;
    public int groupSecLevel;
    public int groupSecLevelInfo;
    public int groupTypeFlag;
    public int isAllowModifyConfGroupName;
    public int isConfGroup;
    public int isModifyConfGroupFace;
    public int isModifyConfGroupName;
    public boolean isTop;
    public String joinGroupAuth;
    public int maxMemberNum;
    public int memberNum;
    public String ownerUid;
    public int privilegeFlag;
    public String remarkName;
    public String richFingerMemo;
    public int shutUpAllTimestamp;
    public int shutUpMeTimestamp;
}
